### ISSUE TITLE
Difficulty in Using 3proxy for UDP Traffic via SOCKS5 Proxy

### ISSUE THREAD

**Issue by Luigi31415** [3proxy/3proxy#1068]
# Issue
I encountered a problem while testing 3proxy for routing UDP traffic using a SOCKS5 proxy setup. My test environment consisted of three computers connected via a VPN, as illustrated in the diagram below:
![Network Diagram](https://github.com/user-attachments/assets/66af70be-d197-4eb3-924e-dc279d5a3e66)
## 3proxy Configuration
The initial 3proxy configuration file used in this setup was as follows:
```
log ./udp_proxy.log
logformat "- +_L%Y-%m-%d %H:%M:%S | %N | %E | %C | %R:%r | %O %I | %1-1T | %2-2T"

nscache 65535
nscache6 65535
nserver 8.8.8.8

auth none

noforce

socks -p3044 -u -n -a -i0.0.0.0 -osTCP_NODELAY -ocTCP_NODELAY -s0

flush
```
### Problem Encountered
When testing this setup, the UDP request from the client timed out, and the following log entry was recorded:
```
2024-08-28 16:37:05 | SOCKS | 00000 | 0.0.0.0 | 0.0.0.0:0 | 0 0 | Accepting | connections
2024-08-28 16:37:39 | SOCK5 | 00100 | 100.101.52.31 | 0.0.0.0:0 | 0 0 | UDPMAP | 0.0.0.0:0
```
The error code `00100` indicated an issue with the UDP mapping.
## Experimentation with Configuration
To troubleshoot the problem, I made a slight modification to the 3proxy configuration by commenting out the DNS server setting:
```
log ./udp_proxy.log
logformat "- +_L%Y-%m-%d %H:%M:%S | %N | %E | %C | %R:%r | %O %I | %1-1T | %2-2T"

nscache 65535
nscache6 65535
# nserver 8.8.8.8

auth none

noforce

socks -p3044 -u -n -a -i0.0.0.0 -osTCP_NODELAY -ocTCP_NODELAY -s0

flush
```
### Results

After applying this change, the request was successfully processed, and the log file returned a success code `00000`:
```
2024-08-28 16:39:07 | SOCKS | 00000 | 0.0.0.0 | 0.0.0.0:0 | 0 0 | Accepting | connections
2024-08-28 16:39:09 | SOCK5 | 00000 | XX.XX.XX.31 | XX.XX.XX.81:12345 | 5 11 | UDPMAP | 0:51160
```

**Comment by z3APA3A** [comment]
Try to use version from master, this issues should be resolved

**Comment by NaturalT314** [comment]
Hello @z3APA3A, Thanks for your response.
I tried compiling 3proxy from main and that wasn't fixed yet.

**Comment by z3APA3A** [comment]
1. Try to add `internal` and `external` to your configuration (external is required in some cases to report external IP address to client)
2. Try 0.9.5, i think this issue must be fixed with https://github.com/3proxy/3proxy/commit/f9347c2f8bb9988de9a572d89526cb64a8e4f804 - it was in master branch.

if problem  still exists, make a wireshark/tcpdump of traffic between client and proxy, send it to 3proxy@3proxy.ru

**Comment by Luigi31415** [comment]
That seems to work, thanks.
I'm wondering if there is a way to make it work without having an external ip, if I have a server behind a NAT for example.

**Comment by z3APA3A** [comment]
It depends on client, not on 3proxy. 3proxy uses external IP to report it to client, so it means proxy client needs to know external IP to function correctly.
